- type: job
  id: Captain
  name: job-name-captain
  description: job-description-captain
  playTimeTracker: JobCaptain
  requirements:
    - !type:RoleTimeRequirement
      role: JobQuartermaster
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: JobChiefEngineer
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: JobChiefMedicalOfficer
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: JobHeadOfSecurity
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: JobHeadOfPersonnel
      time: 7200 # 2 hours
    - !type:RoleTimeRequirement
      role: JobJudge
      time: 7200 # 2 hours
  weight: 20
  startingGear: CaptainGear
  icon: "JobIconCaptain"
  requireAdminNotify: true
  joinNotifyCrew: true
  supervisors: job-supervisors-centcom
  canBeAntag: false
  accessGroups:
  - AllAccess
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
      - type: CommandStaff

- type: startingGear
  id: CaptainGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    eyes: ClothingEyesGlassesSunglasses
    gloves: ClothingHandsGlovesCaptain
    id: CaptainPDA
    ears: ClothingHeadsetAltCommand
  storage:
    back:
    - BoxSurvival
    - Flash
    # - StationCharter
