- type: job
  id: Lawyer
  name: job-name-lawyer
  description: job-description-lawyer
  playTimeTracker: JobLawyer
  startingGear: LawyerGear
  requirements:
    - !type:RoleTimeRequirement
      role: JobClerk
      time: 3600 # 1 hour
  icon: "JobIconLawyer"
  supervisors: job-supervisors-justice
  access:
  - Service
  - Lawyer
  - Brig
  - Maintenance

- type: startingGear
  id: LawyerGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    id: LawyerPDA
    ears: ClothingHeadsetSecurity
    # TODO add copy of space law
  inhand:
    - BriefcaseBrownFilled
  #storage:
    #back:
    #- Stuff
