- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  playTimeTracker: AntagNukeops
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:RoleTimeRequirement
    role: AntagNukeops
    time: 3600 # 1 hour
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:RoleTimeRequirement
    role: AntagNukeops
    time: 3600 # 1 hour
  guides: [ NuclearOperatives ]

#Nuclear Operative Gear
- type: startingGear
  id: SyndicateOperativeGearFull
  equipment:
    jumpsuit: ClothingUniformJumpsuitOperative
    back: ClothingBackpackDuffelSyndicate
    mask: ClothingMaskGasSyndicate
    eyes: ClothingEyesHudSyndicate
    ears: ClothingHeadsetAltSyndicate
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterHardsuitSyndie
    shoes: ClothingShoesBootsCombatFilled
    id: SyndiPDA
    pocket1: DoubleEmergencyOxygenTankFilled
    pocket2: BaseUplinkRadio40TC
    belt: ClothingBeltMilitaryWebbing
  storage:
    back:
    - BoxSurvivalSyndicate
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - DeathAcidifierImplanter

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    neck: SyndicateWhistle
    outerClothing: ClothingOuterHardsuitSyndieCommander
  inhand:
    - NukeOpsDeclarationOfWar

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFull
  equipment:
    eyes: ClothingEyesHudSyndicateAgent
    outerClothing: ClothingOuterHardsuitSyndieMedic
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiAgentPDA
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - SyndiHypo
    - BoxSurvivalSyndicate
    - SawAdvanced
    - Cautery
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - HandheldHealthAnalyzer
    - CombatMedipen
    - DeathAcidifierImplanter

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: BaseUplinkRadio60TC
